package com.plugin.frege.completion

object FregeKeywords {
    const val ABSTRACT = "abstract"
    const val AS = "as"
    const val CASE = "case"
    const val CLASS = "class"
    const val INTERFACE = "interface"
    const val DATA = "data"
    const val DEFAULT = "default"
    const val DERIVING = "deriving"
    const val DERIVE = "derive"
    const val DO = "do"
    const val ELSE = "else"
    const val FALSE = "false"
    const val FOREIGN = "foreign"
    const val FORALL = "forall"
    const val IF = "if"
    const val IMPORT = "import"
    const val IN = "in"
    const val INFIX = "infix"
    const val INFIXL = "infixl"
    const val INFIXR = "infixr"
    const val INSTANCE = "instance"
    const val LET = "let"
    const val NATIVE = "native"
    const val NEWTYPE = "newtype"
    const val OF = "of"
    const val PACKAGE = "package"
    const val PURE = "pure"
    const val MODULE = "module"
    const val PRIVATE_MODIFIER = "private"
    const val PROTECTED_MODIFIER = "protected"
    const val PUBLIC_MODIFIER = "public"
    const val THEN = "then"
    const val THROWS = "throws"
    const val TRUE = "true"
    const val TYPE = "type"
    const val WHERE = "where"
}
